config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "products#index"
  resource :products
  resource :cart_elements, only: [:create, :destroy]
  resource :carts, only: [:update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/applied_voucher.rb
class AppliedVoucher < ApplicationRecord
  belongs_to :voucher
  belongs_to :cart

  validates :voucher_id, uniqueness: { scope: :cart_id }
  validate :verify_min_amount
  validate :verify_product_categories

  private

  def verify_min_amount
    if voucher
      message = "You must spend at least £#{voucher.min_amount} to use this coupon"
      errors.add(:base, message) unless cart.total_price > voucher.min_amount
    end
  end

  def verify_product_categories
    if voucher && !voucher.categories.empty?
      message = "At least one item from #{categories_to_string} is needed"

      errors.add(:base, message) unless cart.cart_elements.any? do |element|
        voucher.categories.include? element.product.category
      end
    end
  end

  def categories_to_string
    if voucher.categories
      voucher.categories.reduce("") { |string, cat| string += "#{cat.name} " }
    end
  end
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_elements
  has_many :applied_vouchers
  has_many :vouchers, through: :applied_vouchers

  def total_price
    cart_elements.empty? ? 0 : sum_of_cart_elements_prices
  end

  def total_voucher_amount
    vouchers.empty? ? 0 : sum_of_vouchers_amounts
  end

  def final_price
    result = total_price - total_voucher_amount
    result < 0 ? 0 : result
  end

  private

  def sum_of_cart_elements_prices
    cart_elements.reduce(0) { |sum, element| sum += element.price  }
  end

  def sum_of_vouchers_amounts
    vouchers.reduce(0) { |sum, element| sum += element.discount_amount  }
  end
end

app/models/cart_element.rb
class CartElement < ApplicationRecord
  belongs_to :cart
  belongs_to :product
  validate :available_in_stock

  def price
    self.product.price * self.quantity
  end

  private

  def available_in_stock
    errors.add(:base, "Not enough items available in stock") unless product.stock >= quantity
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
  has_and_belongs_to_many :vouchers
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category

  def price
    self[:price] - discount_amount
  end

  def original_price
    self[:price]
  end

  def is_discounted?
    self[:price] > price
  end
end

app/models/voucher.rb
class Voucher < ApplicationRecord
  has_many :applied_vouchers
  has_many :carts, through: :applied_vouchers
  has_and_belongs_to_many :categories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_cart

  def current_cart
    if session[:cart_id] && Cart.exists?(session[:cart_id])
      Cart.find(session[:cart_id])
    else
      Cart.create
    end
  end
end

app/controllers/cart_elements_controller.rb
class CartElementsController < ApplicationController

  def create
    @cart = current_cart
    cart_el = @cart.cart_elements.where(product_id: prod_id).first_or_initialize
    if cart_el.increment(:quantity).valid?
      cart_el.save
      flash[:notice] = "Product added to cart"
    else
      flash[:errors] = cart_el.errors.full_messages.to_sentence
    end
    session[:cart_id] = @cart.id
    redirect_to root_path
  end

  def destroy
    @cart_element = CartElement.find(params[:id])
    @cart_element.destroy
    current_cart.applied_vouchers.each do |applied|
      applied.destroy unless applied.valid?
    end
    redirect_to root_path
  end

  private

  def prod_id
    product_params[:product_id]
  end

  def product_params
    params.permit(:product_id)
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def update
    voucher = Voucher.where(code: code).first
    applied = AppliedVoucher.new(cart: current_cart,
                                 voucher: voucher)
    if applied.save
      flash[:notice] = "Coupon Applied!"
    else
      flash[:errors] = applied.errors.full_messages.to_sentence
    end
    redirect_to root_path
  end

  private

  def code
    voucher_params[:voucher_code]
  end

  def voucher_params
    params.permit(:voucher_code)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @categories = Category.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_element_helper.rb
module CartElementHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shop</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="/">Shop</a>
        </div>
      </div>
    </nav>
    <% flash.each do |key, value| %>
      <%= content_tag :div, value, class: "col-md-8", id: "flash #{key}" %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<div class="col-md-6 col-xs-12" id="products">
  <h1>Products</h1>
  <% @categories.each do |cat| %>
    <h2><%= cat.name %></h2>
    <div class="table">
      <% cat.products.each do |prod| %>
        <div class="row">
          <span class="col-md-6 col-xs-6" >
            <%= "#{prod.name}" %>
          </span >
          <span class="col-md-2 col-xs-2">
            <del><%= "£#{prod.original_price}" if prod.is_discounted? %></del>
          </span>
          <span class="col-md-2 col-xs-2">
            <%= "£#{prod.price}" %>
          </span>
          <span class="col-md-2 col-xs-2">
            <%= link_to 'Add To Cart', cart_elements_path(product_id: prod.id),
                        method: :post,
                        class: "btn btn-success btn-xs",
                        id: "add_to_cart_#{prod.id}" %>
          </span>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

<div class="col-md-6 col-xs-12" id="cart">
  <h3>Cart</h3>

  <%-# List of all elements in the cart  -%>

  <div class="table">
    <% current_cart.cart_elements.each do |cart_el| %>
      <div class="row">
        <span class="col-md-6 col-xs-6" >
          <%= "#{cart_el.product.name}" %>
        </span >
        <span class="col-md-2 col-xs-2">
          <%= "#{cart_el.quantity}" %>
        </span>
        <span class="col-md-2 col-xs-2">
          <%= "£#{cart_el.price}" %>
        </span>
        <span class="col-md-2 col-xs-2">
          <%= link_to "Remove", cart_elements_path(id: cart_el.id),
                      method: :delete,
                      class: "btn btn-danger btn-xs",
                      id: "remove_cart_element_#{cart_el.product.id}" %>
        </span>
      </div>
    <% end %>
    <%-# End of element list  -%>


    <%= form_tag(carts_path(current_cart), method: 'patch') do %>
      Voucher
      <%= text_field_tag "voucher_code" %>
      <%= submit_tag "Submit", class: "btn btn-xs", id: "voucher_submit" %>
    <% end %>
    <div class="row" id="cart_price_row">
      <span class="col-md-8 col-xs-8" >
        <b>Total:</b>
      </span >
      <span class="col-md-4 col-xs-4" >
        <%= "£#{current_cart.total_price}" %>
      </span >
    </div>

    <% if !current_cart.vouchers.empty?  %>
      <div class="row" id="voucher_total_row">
        <span class="col-md-8 col-xs-8" >
          <b>Discount:</b>
        </span >
        <span class="col-md-4 col-xs-4" >
          <%= "- £#{current_cart.total_voucher_amount}" %>
        </span >
      </div>

      <div class="row" id="final_price_row">
        <span class="col-md-8 col-xs-8" >
          <b>Final Price:</b>
        </span >
        <span class="col-md-4 col-xs-4" >
          <%= "£#{current_cart.final_price}" %>
        </span >
      </div>
    <% end %>
  </div>
</div>